### ISSUE TITLE
Stream Getting Stopped in Consume Kafka Notebook. 

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale#2] opened 2019-09-04 14:36 UTC
In the Exercise 3 Task 2 , While Executing Cells in Consume Kafka Notebook the stream is getting stopped every time and because of the  Stream issue data can't be generated in Powerbi.

![Screenshot (26)2](https://user-images.githubusercontent.com/45102602/64267044-4fd36500-cf53-11e9-85c0-c897852cd1a1.png)

**Comment by joelhulen** [comment] 2019-09-04 23:54
I'll run through this lab in the next day or two and see if I can reproduce this issue. I notice that you are using a hosted environment. It'll be interesting to see if the issue is with the lab artifacts or your environment setup.

**Comment by sumitmalik51** [comment] 2019-09-05 04:33
Yeah sure , please check.

**Comment by DawnmarieDesJardins** [comment] 2019-09-10 16:27
Hi @sumitmalik51 
We will do our best to get this fixed for you.  Please note, any time you open in issue and have an upcoming presentation, we need that information and the date of the presentation in the issue.  We have many workshops and this will help us prioritize fixes.

**Comment by sumitmalik51** [comment] 2019-09-10 17:43
Thanks for your reply @DawnmarieDesJardins , We have 35 attendees for a scheduled Workshop that have to be delivered by tomorrow.

**Comment by joelhulen** [comment] 2019-09-10 18:58
@sumitmalik51 I have started the lab from scratch, using a brand new VM, and followed all of the steps up until the end of the notebook you are having issues with. Everything is working fine for me. I suspect you have missed a step either in the `before the hands-on lab`, or in the `hands-on lab step-by-step` guide.

![image](https://user-images.githubusercontent.com/5950304/64641641-96edaa00-d3da-11e9-856d-bcc660dd6ac9.png)

Furthermore, I have verified that the data is being written to the PostegreSQL table by executing cells 19-23 below that one:

![image](https://user-images.githubusercontent.com/5950304/64641754-d3b9a100-d3da-11e9-99bc-eff956c36f19.png)

The error you stated about the "Stream issue can't be generated in Powerbi" doesn't make sense. Can you copy and paste the exact error you see when you expand the stream details in the cell?

I suspect perhaps the Service Principal did not get created, or perhaps one of the secrets you added to Key Vault were incorrectly entered in Exercise 2 (https://github.com/microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Real-time%20data%20with%20Azure%20Database%20for%20PostgreSQL%20Hyperscale.md#Exercise-2-Add-secrets-to-Key-Vault-and-configure-Azure-Databricks). Please go back and verify all those steps.

**Comment by DawnmarieDesJardins** [comment] 2019-09-10 21:46
@sumitmalik51 
Hi Sumit.  This workshops was already scheduled for a test/fix this month and, as @joelhulen was reviewing your opened issue, he completed that for us early.  I've QC'd and merged the PR and I've updated the HTML links.  For your workshop, please make sure you are using documents dated September 2019.  That is where you will find the most current information and instructions.
Have a great presentation!  Dawnmarie

**Comment by DawnmarieDesJardins** [comment] 2019-09-16 16:31
Closing as address in last test/fix.

**Closed by DawnmarieDesJardins** 2019-09-16 16:31 UTC
